"""add: document status progress

Revision ID: 4728b23662b6
Revises: e156fc5f37bf
Create Date: 2026-02-26 17:50:39.639421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4728b23662b6'
down_revision: Union[str, Sequence[str], None] = 'e156fc5f37bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('description', sa.String(), nullable=True))
    op.add_column('document_types', sa.Column('risk_rules', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('ai_progress', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'ai_progress')
    op.drop_column('document_types', 'risk_rules')
    op.drop_column('document_types', 'description')
    # ### end Alembic commands ###
