"""add column document risk level

Revision ID: 97d8d7c63d6d
Revises: 4728b23662b6
Create Date: 2026-02-26 20:38:46.086113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d8d7c63d6d'
down_revision: Union[str, Sequence[str], None] = '4728b23662b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('risk_reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'risk_reasoning')
    op.drop_column('documents', 'risk_level')
    # ### end Alembic commands ###
