"""create add column document type

Revision ID: d4d77a6a7ea7
Revises: 68f146620c8b
Create Date: 2026-02-15 20:53:44.468173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d77a6a7ea7'
down_revision: Union[str, Sequence[str], None] = '68f146620c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_types', ['document_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type_id')
    # ### end Alembic commands ###
